# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{has_many_versions}
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua Hull"]
  s.date = %q{2009-12-03}
  s.email = %q{joshbuddy@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "lib/has_many_versions.rb",
    "rails/init.rb",
    "spec/add_spec.rb",
    "spec/database.yml",
    "spec/delete_spec.rb",
    "spec/history_spec.rb",
    "spec/rollback_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/update_spec.rb"
  ]
  s.homepage = %q{http://github.com/joshbuddy/has_many_versions}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Versioning for has_many relationships}
  s.test_files = [
    "spec/add_spec.rb",
    "spec/delete_spec.rb",
    "spec/history_spec.rb",
    "spec/rollback_spec.rb",
    "spec/spec_helper.rb",
    "spec/update_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

